# Generated by Django 5.2 on 2025-04-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
