# Generated by Django 5.2 on 2025-06-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0001_initial'),
        ('webinar', '0016_alter_testresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar'),
        ),
    ]
