# Generated by Django 5.2 on 2025-06-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0002_testresult_webinar'),
        ('webinar', '0017_responsequestionaire_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='test_qr/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='CertificateTemplate/')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar')),
            ],
        ),
    ]
