# Generated by Django 5.2 on 2025-06-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0003_testqr_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='participant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
