# Generated by Django 5.2 on 2025-06-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0004_certificatetemplate_participant_and_more'),
        ('webinar', '0021_rename_speaker_email_speaker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testqr',
            name='test_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_qr', to='webinar.test_question'),
        ),
    ]
