# Generated by Django 5.2 on 2025-06-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0005_alter_testqr_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testqr',
            old_name='test_id',
            new_name='test',
        ),
    ]
