# Generated by Django 5.2 on 2025-06-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0006_rename_test_id_testqr_test'),
        ('webinar', '0021_rename_speaker_email_speaker_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testqr',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='testqr',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_qr', to='webinar.webinar'),
        ),
    ]
