# Generated by Django 5.2.3 on 2025-06-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0007_testqr_type_alter_testqr_test'),
        ('webinar', '0023_alter_responsequestionaire_webinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testqr',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_qr', to='webinar.webinar'),
        ),
        migrations.CreateModel(
            name='EvalQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='eval_qr/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_qr', to='webinar.webinar')),
            ],
        ),
    ]
