# Generated by Django 5.2.3 on 2025-07-03 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0008_alter_testqr_test_evalqr'),
        ('webinar', '0024_alter_webinarattendees_webinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='webinar.webinar'),
        ),
    ]
