# Generated by Django 5.2.3 on 2025-07-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0009_alter_certificatetemplate_webinar'),
        ('webinar', '0024_alter_webinarattendees_webinar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='type',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='webinar.webinar'),
        ),
    ]
