# Generated by Django 5.1.7 on 2025-03-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='number_of_speaker',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='webinarattendees',
            name='school_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
