# Generated by Django 5.1.7 on 2025-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_responsequestionaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker',
            new_name='speaker_name',
        ),
        migrations.AddField(
            model_name='speaker',
            name='speaker_email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
