# Generated by Django 5.2 on 2025-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_rename_speaker_speaker_speaker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsequestionaire',
            name='q6',
        ),
        migrations.AddField(
            model_name='responsequestionaire',
            name='catergory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responsequestionaire',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsequestionaire',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
