# Generated by Django 5.2 on 2025-05-07 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0005_remove_responsequestionaire_q6_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('MC', 'MULTIPLE_CHOICE'), ('FB', 'FILL_IN_THE_BLANKS'), ('TF', 'TRUE_OR_FLASE')], max_length=20)),
                ('question_id', models.IntegerField()),
                ('question', models.TextField()),
                ('user_answered', models.TextField(blank=True, null=True)),
                ('correct_answered', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar')),
            ],
        ),
    ]
