# Generated by Django 5.2 on 2025-05-11 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0006_testresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresponse',
            name='correct_answered',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='webinar',
        ),
        migrations.AlterField(
            model_name='testresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Test_Questionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('test_type', models.CharField(blank=True, max_length=100, null=True)),
                ('question_type', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_anwered', models.CharField(blank=True, max_length=200, null=True)),
                ('webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice_text', models.CharField(blank=True, max_length=200, null=True)),
                ('test_questionaire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.test_questionaire')),
            ],
        ),
        migrations.AddField(
            model_name='testresponse',
            name='test_questionaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.test_questionaire'),
        ),
    ]
