# Generated by Django 5.2 on 2025-05-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0007_remove_testresponse_correct_answered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_Questionaire',
            new_name='Test_Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='test_questionaire',
            new_name='test_question',
        ),
    ]
