# Generated by Django 5.2 on 2025-05-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0008_rename_test_questionaire_test_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Choice_text',
            new_name='choice_text',
        ),
    ]
