# Generated by Django 5.2 on 2025-05-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0009_rename_choice_text_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_question',
            old_name='correct_anwered',
            new_name='correct_answered',
        ),
    ]
