# Generated by Django 5.2 on 2025-05-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0010_rename_correct_anwered_test_question_correct_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text_option',
        ),
        migrations.RenameField(
            model_name='testresponse',
            old_name='test_questionaire',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='test_question',
        ),
        migrations.RemoveField(
            model_name='responsequestionaire',
            name='catergory',
        ),
        migrations.RemoveField(
            model_name='responsequestionaire',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='responsequestionaire',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testresponse',
            name='user_answered',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinar.test_question'),
        ),
        migrations.AddField(
            model_name='responsequestionaire',
            name='q6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresponse',
            name='user_input',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='responsequestionaire',
            name='q5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test_question',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='test_question',
            name='question_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='test_question',
            name='test_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
