# Generated by Django 5.2 on 2025-05-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0013_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_question',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='webinar.webinar'),
        ),
    ]
