# Generated by Django 5.2 on 2025-06-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0015_testresponse_is_correct_testresponse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_reponse', to='webinar.test_question'),
        ),
    ]
