# Generated by Django 5.2 on 2025-06-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0016_alter_testresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsequestionaire',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
