# Generated by Django 5.2 on 2025-06-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0018_webinarattendees_user_alter_webinarattendees_webinar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='time',
            field=models.TimeField(max_length=20),
        ),
    ]
