# Generated by Django 5.2 on 2025-06-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0019_alter_webinar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='img',
            field=models.ImageField(blank=True, default='UserProfile/1.jpg', null=True, upload_to='SpeakerProfile'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='webinar.webinar'),
        ),
    ]
