# Generated by Django 5.2 on 2025-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0020_speaker_img_alter_speaker_webinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_name',
            new_name='name',
        ),
    ]
