# Generated by Django 5.2.3 on 2025-06-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0022_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsequestionaire',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='webinar.webinar'),
        ),
    ]
